<?php


namespace CentreBundle\Repository;

/**
 * notecentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notecentreRepository extends \Doctrine\ORM\EntityRepository
{

}
